name: panoptes-tutorials

channels:
  - astropy


dependencies:
  - pip
  - python>=3.7
  - numpy
  - matplotlib
  - pandas
  - seaborn
  - pymongo
  - pip:
    - astroplan
    - panoptes-utils
    - -e git+git://github.com/panoptes/POCS@develop#egg=pocs
    
